// Generated by https://quicktype.io

export interface NoticiasI {
  status:       string;
  totalResults: number;
  articles:     Article[];
}

export interface Article {
  source:      Source;
  author:      null | string;
  title:       string;
  description: null | string;
  url:         string;
  urlToImage:  null | string;
  publishedAt: string;
  content:     null | string;
}

export interface Source {
  id:   ID;
  name: Name;
}

export enum ID {
  Techcrunch = "techcrunch",
}

export enum Name {
  TechCrunch = "TechCrunch",
}
